// Generated by CoffeeScript 1.10.0
(function() {
  var buttons;

  buttons = [
    {
      name: "twitter",
      "class": "icon ion-social-twitter",
      link: "https://twitter.com/pablopunk"
    }, {
      name: "github",
      "class": "icon ion-social-github",
      link: "https://github.com/pablopunk"
    }, {
      name: "youtube",
      "class": "icon ion-social-youtube",
      link: "https://youtube.com/varelapol13"
    }, {
      name: "chronocube",
      "class": "icon ion-cube",
      link: "https://pablopunk.github.io/chronocube"
    }
  ];

  $(function() {
    var b, button_html, i, len, results;
    results = [];
    for (i = 0, len = buttons.length; i < len; i++) {
      b = buttons[i];
      button_html = "<div class='three columns'><a class='button' href='" + b.link + "'><i class='" + b["class"] + "'></i> " + b.name + "</a></div>";
      results.push($('.container').append(button_html));
    }
    return results;
  });

}).call(this);
